### PR TITLE
Add option to disable nginx access logs

### PR DESCRIPTION
**Pull request by rogierlommers**

### CODE REVIEW

**Comment by rogierlommers** [comment]
By the way, can you give me instruction how you normally test changes?

**Comment by xirixiz** [comment]
DSMR Reader Docker is here for a while now. Back then, I mainly had a background in operations and mainly bash scripting :). I guess I don't need to explain I found testing unnecessary.

Anyway, was thinking to spend some time in 2023 to rewrite things in a TTD way and get rid of all the bash things.

**Comment by rogierlommers** [comment]
> DSMR Reader Docker is here for a while now. Back then, I mainly had a background in operations and mainly bash scripting :). I guess I don't need to explain I found testing unnecessary.
> 
> Anyway, was thinking to spend some time in 2023 to rewrite things in a TTD way and get rid of all the bash things.

No problem, I was just thinking how I could easily test my changes locally.
Let me know if you need something more!

**Comment by xirixiz** [comment]
When I merge something to the develop branch, a pipeline builds a new release with de development tag. That's how I personally validate a new baked image.

**Pull request merged**
