### PR TITLE
CI refactor, publish image to GHCR

### LINKED ISSUE #324: Consider alternate image registry to Docker Hub
### Request

Since Docker Hub has been applying rate limits on image pulls for a while now, and their more recent move to scrap free teams I feel that Docker Hub is becoming more and more hostile towards the OSS/hobbyist community.

I would like to propose providing GitHub Container Registry as an alternative (or completely switching over to it) for the project.

Would you be open to this? If so, I'd be willing to write up a PR to help implement.

### Additional information

Additional CI improvement suggestions:
- Perhaps moving the build to use `docker buildx` to create an integrated manifest instead of writing and pushing separate manifests
- Use the native Github Actions concurrency feature (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) to cancel previous workflows

### PR DESCRIPTION
**Pull request by bjw-s**
This PR makes it so that the resulting Docker image is pushed to GitHub Container registry

This PR also aims to improve the CI by 
- use `docker buildx` to perform the multiarch build
- moving some things to the Dockerfile build
- use available GitHub actions to reduce the amount of scripting in the pipeline
- use native GitHub concurrency to make sure only a single docker build runs at a given time

Because the resulting manifest is now a true multi-arch manifest, the tagging scheme has been changed. This could be considered a "breaking" change in SemVer terms.

Fixes #324 

Working example (I have only commented out the actual image pushing and logging in to Docker Hub):
https://github.com/bjw-s/dsmr-reader-docker/actions/runs/4438109116

### CODE REVIEW

**Review by onedr0p — APPROVED** [review]

**Comment by xirixiz** [comment]
Love it @onedr0p! I really appreciate this improvement! Sometimes it's "just" working and improvements will then only happen when there is some spare time left. This removes a lot of unnecessary build code as well.

**Comment by bjw-s** [comment]
> Love it @onedr0p! I really appreciate this improvement! Sometimes it's "just" working and improvements will then only happen when there is some spare time left. This removes a lot of unnecessary build code as well.
> 
> I`ll validate it and merge it Tonight.

onedr0p is _not_ stealing my thunder again :P (he'll understand the joke there)
But I am glad that you like the changes. I'm doing some final tests (hence the force pushes) but those will be done in a little bit

**Comment by xirixiz** [comment]
Everything is working like a charm @bjw-s. Many thanks again for this great contribution. In the next release I`ll manage your name in the README ✌️

**Comment by bjw-s** [comment]
Sweet! Glad it's working as designed :) Thanks for merging!

**Pull request merged**
