### PR TITLE
Update base image to python:3-alpine3.17

### PR DESCRIPTION
**Pull request by stejoo**

### CODE REVIEW

**Comment by stejoo** [comment]
Alpine 3.17 points metapkg `postgresql-client` to `postgresql15-client`. Adds support for Postgresql 15 databases.

**Comment by xirixiz** [comment]
Hi @stejoo, did you validate a build with this image? I've tested it a while ago, but there were some issues with Python library dependencies....

If not tested, I can test it.

**Comment by stejoo** [comment]
I would have liked to test it but did not. Reason for that is I was unable to build the container using the `Dockerfile`, because of these COPY statements:

https://github.com/xirixiz/dsmr-reader-docker/blob/f08ee1283106a7e5722fdc314e844c0cfd95cae6/Dockerfile#L40-L42

I was doing this inbetween talks at a conference, and it wasn't immediately clear to me how you prepared your `/tmp` beforehand. So I thought maybe some automated testing is set up to kick off when there is a PR. :wink: And left it at that for the moment.

I came home a short while ago, had a second look and found [build_release.yml](https://github.com/xirixiz/dsmr-reader-docker/blob/f08ee1283106a7e5722fdc314e844c0cfd95cae6/.github/workflows/build_release.yml) contains various preparations that populate `/tmp`.

I would like to test and try to iron out any kinks if I can. I could try to replicate the actions described in the build_release.yml file on my system by hand. Or do you have some easier way to perform the required actions locally?

**Comment by stejoo** [comment]
I created a `build.sh` script from your Github Actions to locally build and test the container image. (If anybody is interested in that I could put it in a gist or pastebin somewhere).

What happened first is a conflict between `openssl` and `libressl`. The packages touch the same files and therefor come in conflict with eachother. Alpine 3.17 upgraded OpenSSL to version 3.x up from (legacy) v1.1.x. LibreSSL seemed to have been present to add various functionalities OpenSSL v1.1 did not offer. Removing `libressl-dev` as a package allowed me to successfully build the container image.

Running it is where it goes wrong now:
```
2023/02/20 13:14:18 [emerg] 312#312: "upstream" directive is not allowed here in /etc/nginx/conf.d/dsmr-webinterface.conf:1
nginx: [emerg] "upstream" directive is not allowed here in /etc/nginx/conf.d/dsmr-webinterface.conf:1
```

I started to compare the Nginx configurations. The ones I compared matter are the main `nginx.conf` and the `dsmr-webinterface.conf` file. 
* The `nginx.conf` added two commented lines. No difference there.
* The `dsmr-webinterface.conf` is added by us. I haven't changed it, it is still the same.

Maybe a difference in the nginx version? 
* current working: `nginx-1.22.1-r0 x86_64 {nginx} (BSD-2-Clause) [installed]`
* new alpine 3.17: `nginx-1.22.1-r0 x86_64 {nginx} (BSD-2-Clause) [installed]`

No difference in version. Could be in build options, haven't dug that deep yet.

When I find the time I will try to dig deeper. Currently, where I am at: nginx isn't starting because of a configuration issue.

**Comment by xirixiz** [comment]
Great! This is indeed where I also bumped into and never spend time on it to solve this. I`ll create a dev branch so dev builds will be created for testing. If you like, you could also work on the dev branch and use the github pipelines instead. I`ll check it this week.

**Comment by stejoo** [comment]
I think I've got it. :smile: 

Got rid of LibreSSL. Did make an assumption it is not needed anymore, because OpenSSL now offers the same functionality. But that will require testing of different configurations and use cases I guess.

The nginx configuration went awry because the `/etc/nginx/conf.d` was a symlink to `/etc/nginx/http.d`. Nginx includes configuration files from both, but those are loaded in different context. Small snippet of the `nginx.conf`:

```
[..]
# Include files with config snippets into the root context.
include /etc/nginx/conf.d/*.conf;

http {
[..]
	# Includes virtual hosts configs.
	include /etc/nginx/http.d/*.conf;
}
```

The `http.d/dsmr-webinterface.conf` contains an `upstream { }` and a `server { }` block, which need to exist within a `http{}` block and not outside it. The first include would find them and there the story would end. I turned `/etc/nginx/conf.d` in a real, empty, directory. Causing `dsmr-webinterface.conf` to be include within the `http{ }` block.

Performed a quick test: it seems to now be working for me :stuck_out_tongue_winking_eye:

**Comment by xirixiz** [comment]
Great job! Thanks for helping out. I'll validate the changes as well and if all is good, I can merge it to a new release!

Thanks again for your contribution! Very much appreciated 🎉

**Comment by xirixiz** [comment]
Sorry, I have been quiet busy. I wlll respond asap!

**Comment by stejoo** [comment]
Maak je niet druk, ik weet hoe dat gaat; er zijn belangrijkere dingen in het leven. Het is maar een update van het spul. Er loopt geen bloed uit :wink: 

No worries! I know what it's like; some things in life are more important. It is just an update. Not something of utmost importance. :wink:

**Pull request merged**
