### PR TITLE
Fix issue with docker secrets

### PR DESCRIPTION
**Pull request by goegol**
And some minor improvements, see changelog

### CODE REVIEW

**Comment by xirixiz** [comment]
What a coincidence! I was just about to upgrade Alpine and Python :). Thanks for the PR. Will do some testing and draft a new release somewhere next week.

**Comment by goegol** [comment]
Lol! thnx!
Can you also upgrade the postgres client to support postgres 17?
Or shall i send mr?

**Comment by xirixiz** [comment]
I`ll fix it as well. Thanks for the comment.

I`ll draft a development image. If you want to you can test it.

**Comment by xirixiz** [comment]
https://github.com/xirixiz/dsmr-reader-docker/actions/runs/12544876623

Build is running. If it fails I`ll have a look later Today or this week.

**Comment by xirixiz** [comment]
Development Docker image is ready. Cannot use Python 3.13 yet as DSMR Reader isn't compatible with it. So now using the latest stable Alpine image with Python 3.12

https://hub.docker.com/r/xirixiz/dsmr-reader-docker/tags

Please let me know if eveything is working as expected.

**Comment by goegol** [comment]
Hi,

Already testing but does not work.
Currently i don't know the root cause, this evening i have more time to investigate, but quick overview:
- it's a fresh install (so clean database)
- using the FILE__ for the secrets
- db connectivity check works
- post_config complains about can't login into database
- dsmr start up and login to database and complains about missing tables (see same messages in database log).

litte bit supprising that post_config complains about can't login into db and dsmr itselfs can login.

**Comment by goegol** [comment]
Logs

```
[ INFO ] Ensure permissions...


[ INFO ] Setting architecture requirements...


[ INFO ] ARM Architecture


[ INFO ] Enabling Docker secrets...


[ INFO ] Docker secret DJANGO_DATABASE_PASSWORD set from FILE__DJANGO_DATABASE_PASSWORD...


[ INFO ] Docker secret DSMRREADER_ADMIN_PASSWORD set from FILE__DSMRREADER_ADMIN_PASSWORD...


[ INFO ] Verifying if the DSMR Reader web credential variables have been set...


[ INFO ] Verifying database connectivity to host: database_postgres with port: 5432...


[ INFO ] Database connectivity successfully verified!


[ INFO ] Running post configuration...

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

    self.connect()

  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 33, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 200, in connect

    self.connection = self.get_new_connection(conn_params)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 33, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection

    connection = Database.connect(**conn_params)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect

    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

psycopg2.OperationalError: connection to server at "database_postgres" (10.0.1.7), port 5432 failed: FATAL:  password authentication failed for user "dsmrreader"
```

**Comment by xirixiz** [comment]
Hmm, it says that password auth fails on the DB. See last line:

psycopg2.OperationalError: connection to server at "database_postgres" (10.0.1.7), port 5432 failed: FATAL:  password authentication failed for user "dsmrreader"

**Comment by goegol** [comment]
yeah but some more errors:
`django.db.utils.OperationalError: connection to server at "database_postgres" (10.0.1.7), port 5432 failed: FATAL:  password authentication failed for user "dsmrreader"

559 static files copied to '/var/www/dsmrreader/static'.

/app/dsmr_parser/parsers.py:41: SyntaxWarning: invalid escape sequence '\d'`

and then after the latest retry it looks like its connect to db, but cant find tables.
That is also what i see in the logs of postgres:

`  File "/usr/local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect

    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

django.db.utils.OperationalError: connection to server at "database_postgres" (10.0.1.7), port 5432 failed: FATAL:  password authentication failed for user "dsmrreader"


[ INFO ] Checking for CLIENT CERTIFICATE AUTHENTICATION configuration...


[ INFO ] ENABLE_CLIENTCERT_AUTH is disabled, nothing to see here. Continuing...


[ INFO ] Checking for NGINX SSL configuration...


[ INFO ] ENABLE_NGINX_SSL is disabled, nothing to see here. Continuing...


[ INFO ] Checking for HTTP AUTHENTICATION configuration...


[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...


[ INFO ] Configuring DSMR Reader to run all processes in a single container with a serial or ipv4 datalogger...


[ INFO ] Using a serial connection for the DSMR Reader remote datalogger...


[ INFO ] Fixing /dev/ttyUSB0 security...


[ INFO ] Adding serial input method configuration settings...


[ INFO ] Adding DSMRREADER_LOGLEVEL to the DSMR Reader configuration...

s6-rc: info: service init-docker-entrypoint successfully started

s6-rc: info: service svc-dsmr-webinterface: starting

s6-rc: info: service svc-dsmr-remote-datalogger: starting

s6-rc: info: service svc-dsmr-datalogger: starting

s6-rc: info: service svc-dsmr-backend: starting

s6-rc: info: service svc-dsmr-webinterface successfully started

s6-rc: info: service svc-nginx: starting

s6-rc: info: service svc-dsmr-webinterface-log: starting

s6-rc: info: service svc-dsmr-remote-datalogger successfully started

s6-rc: info: service svc-dsmr-datalogger successfully started

s6-rc: info: service svc-dsmr-datalogger-log: starting

Starting DSMR Reader - webinterface...

Starting DSMR Reader - datalogger...

s6-rc: info: service svc-nginx successfully started

s6-rc: info: service svc-dsmr-webinterface-log successfully started

s6-rc: info: service svc-dsmr-backend successfully started

s6-rc: info: service svc-dsmr-backend-log: starting

s6-rc: info: service svc-dsmr-datalogger-log successfully started

Starting DSMR Reader - backend...

s6-rc: info: service svc-dsmr-backend-log successfully started

s6-rc: info: service legacy-services: starting

s6-rc: info: service legacy-services successfully started

[2024-12-30 13:19:28 +0100] [133] [INFO] Starting gunicorn 20.1.0

[2024-12-30 13:19:28 +0100] [133] [INFO] Listening at: unix:/tmp/gunicorn--dsmr_webinterface.socket (133)

[2024-12-30 13:19:28 +0100] [133] [INFO] Using worker: sync

[2024-12-30 13:19:28 +0100] [168] [INFO] Booting worker with pid: 168


Testing webservice socket connectivity: 1 second(s) of 10 seconds...Starting DSMR Reader - nginx...

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

psycopg2.errors.UndefinedTable: relation "dsmr_backend_backendsettings" does not exist

LINE 1: ..._backend_backendsettings"."restart_required" FROM "dsmr_back...

                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/app/manage.py", line 10, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 413, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 354, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 398, in execute

    output = self.handle(*args, **options)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/dsmr_backend/mixins.py", line 48, in handle

    self.data = self.initialize()

                ^^^^^^^^^^^^^^^^^

  File "/app/dsmr_backend/management/commands/dsmr_backend.py", line 22, in initialize

    self.sleep_time = BackendSettings.get_solo().process_sleep

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/solo/models.py", line 55, in get_solo

    obj, created = cls.objects.get_or_create(pk=cls.singleton_instance_id)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by xirixiz** [comment]
Kan ook door de Python versie komen, dus dat DSMR Reader nog aanpassingen nodig heeft om te kunnen werken met Python 3.12+. Ik kan de image opnieuw maken op basis van Python 3.11, wat het ook was, maar dan wel op de laatste Alpine versie.

**Comment by goegol** [comment]
het is niet python 3.11 of 3.12 gerelateerd.
Heeft te maken met de FILE__ variable.
FILE__DJANGO_DATABASE_PASSWORD deze uitgezet en even via omgevings variable ingeladen (DJANGO_DATABASE_PASSWORD) en nu werkt alles..

**Comment by xirixiz** [comment]
Oke, dat is mooi, dan kan ik een nieuwe release bouwen.

**Pull request merged**
